feat: improvements and new features
- updates php dependencies
- add pgadmin
- move settings files
- add new settings to php ini
- optimizations and improvements to nginx configuration
- reduces the size of the final image considerably

diff --git a/docker/php/Dockerfile b/docker/php/Dockerfile
--- a/docker/php/Dockerfile
+++ b/docker/php/Dockerfile
@@ -1,83 +1,100 @@
-FROM php:8.2-fpm-alpine
-LABEL MAINTAINER="Vagner Cardoso <vagnercardosoweb@gmail.com>"
+# From
+FROM php:8.2.12-fpm-alpine3.18
 
-# Environments
-ENV TZ=America/Sao_Paulo
-ENV WORKDIR=/var/www/app.dev
+# Labels
+LABEL creatorName="Vagner dos Santos Cardoso"
+LABEL creatorEmail="vagnercardosoweb@gmail.com"
 
 # Set timezone
+ENV TZ=${TZ:-UTC}
 RUN ln -snf /usr/share/zoneinfo/$TZ /etc/localtime && echo $TZ > /etc/timezone
 
-# Updates and installs system dependencies
-RUN apk add --update --no-cache \
-    git \
-    vim \
-    zip \
-    unzip \
-    bash \
-    curl \
-    tzdata \
-    icu-dev \
-    libxml2-dev \
-    libpng-dev \
-    libwebp-dev \
-    libjpeg-turbo-dev \
-    freetype-dev \
-    postgresql-dev \
-    libzip-dev \
-    libxslt-dev \
-    oniguruma-dev \
-    linux-headers \
-    $PHPIZE_DEPS && \
-    rm -rf /var/cache/apk/*
+# Install non-dev dependencies
+RUN set -eux \
+  && apk add --no-cache \
+  git vim zip unzip bash curl tzdata icu-libs \
+  c-client make ca-certificates imap gmp gettext libssh2 \
+  libintl libxslt libpng libwebp libjpeg-turbo freetype imap \
+  linux-headers oniguruma libxslt libpq vips \
+  gmp libzip libxml2 freetds
 
-# Configure php dependency
-RUN docker-php-ext-configure soap --enable-soap
-RUN docker-php-ext-configure gd --enable-gd --with-freetype --with-jpeg --with-webp
-RUN docker-php-ext-configure pcntl --enable-pcntl
-
-# Install php dependencies
-RUN docker-php-ext-install \
-    -j$(nproc) gd \
-    bcmath \
-    xml \
-    soap \
-    mbstring \
-    pdo \
-    pdo_mysql \
-    pdo_pgsql \
-    mysqli \
-    zip \
-    opcache \
-    intl \
-    xsl \
-    pcntl \
-    sockets \
-    exif
-
-# Install lib from pecl
-RUN pecl channel-update pecl.php.net \
-    && pecl install -o -f xdebug \
-    && pecl install -o -f redis \
-    && docker-php-ext-enable xdebug redis \
-    && rm -rf /tmp/pear
+# Install dependencies
+RUN set -eux \
+  && apk add --no-cache --virtual .build_deps \
+  libpng-dev libwebp-dev libjpeg-turbo-dev freetype-dev imap-dev \
+  linux-headers oniguruma-dev libxslt-dev postgresql-dev vips-dev \
+  libssh2-dev gmp-dev libzip-dev libxml2-dev freetds-dev \
+  $PHPIZE_DEPS \
+  \
+  # Php extensions
+  && docker-php-ext-install \
+  mysqli \
+  pdo_mysql \
+  pdo_pgsql \
+  pgsql\
+  bcmath \
+  mbstring \
+  xml \
+  gd \
+  exif \
+  zip \
+  soap \
+  intl \
+  xsl \
+  pcntl \
+  sockets \
+  sysvmsg \
+  sysvsem \
+  sysvshm \
+  opcache \
+  imap \
+  gmp \
+  \
+  # Install xdebug
+  && pecl install -o -f xdebug \
+  && docker-php-ext-enable xdebug \
+  \
+  # Install redis
+  && pecl install -o -f redis \
+  && docker-php-ext-enable redis \
+  \
+  # Install mongodb
+  && pecl install -o -f mongodb \
+  && docker-php-ext-enable mongodb \
+  \
+  # Install apcu
+  && pecl install -o -f apcu \
+  && docker-php-ext-enable apcu \
+  \
+  # Install ssh2 \
+  && pecl install -o -f ssh2 \
+  && docker-php-ext-enable ssh2 \
+  \
+  # Clean php extensions
+  && rm -rf /tmp/pear \
+  && docker-php-source delete \
+  \
+  # Clean up \
+  && apk del --purge .build_deps \
+  && rm -rf /var/cache/apk/*
 
 # Install composer
-COPY --from=composer:latest /usr/bin/composer /usr/bin/composer
+COPY --from=composer:latest /usr/bin/composer /usr/local/bin/composer
 
 # Copy php settings
-COPY ./conf.d ${PHP_INI_DIR}/conf.d
+COPY ./php.ini ${PHP_INI_DIR}/conf.d/99-php.ini
+
+# Copy entrypoint
+COPY ./entrypoint /usr/local/bin/docker-entrypoint
+RUN chmod +x /usr/local/bin/docker-entrypoint
 
 # Workdir
+ENV WORKDIR=/var/www/app
 RUN mkdir -p ${WORKDIR}
 WORKDIR ${WORKDIR}
 
 # Expose port
 EXPOSE 9000
 
-# Copy entrypoint
-COPY ./entrypoint.sh /usr/bin/docker-entrypoint
-RUN chmod +x /usr/bin/docker-entrypoint
-
-# Start
-CMD [ "docker-entrypoint" ]
+# Run entrypoint
+CMD ["docker-entrypoint"]
